### ISSUE TITLE
Docker Diet

### ISSUE THREAD

**Issue by AMS003010** [acmpesuecc/ArcList#16]
Let's supercharge our application with a Docker setup! 🚀 

Task: 🛠️ 
 - Containerize the application by writing a Dockerfile and .dockerignore file
 - Using multi-stage builds, create lean, minimal containers 🐳 to give ArcList the ability to be deployed ANYWHERE !!!

**Comment by Ankur2606** [comment]
I'm taking on this issue . I do wonder about what's the bounty tag  as well as hacknight-2024 for? May you clarify on it

**Comment by AMS003010** [comment]
Sorry but this issue is for participants of Hacknight 2024

**Comment by Ankur2606** [comment]
You have also added hacktoberfest tag on it , therefore It made me puzzled into thinking if it falls under that category . tbh I was just hunting for some easy fixes in order to contribute to hacktoberfest as I was bored . If its for some of your organization or an event then that's fine with me . Let me know if you seek any help further ^^.

**Comment by Roshr2211** [comment]
Please assign me this
